import { Component, OnInit, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ApiService } from '../core/api.service';
import { Campus, UserView } from '../core/models';
import { errorMessage, labelFor } from '../core/presentation';
import { ToastService } from '../core/toast.service';
import { ConfirmDialogComponent } from '../shared/confirm-dialog.component';
import { AdminAcademicComponent } from './admin-academic.component';
import { AdminReferencesComponent } from './admin-references.component';

@Component({standalone:true,imports:[ReactiveFormsModule,AdminAcademicComponent,AdminReferencesComponent,ConfirmDialogComponent],template:`
  <header class="page-header"><div><span class="eyebrow">Configuração institucional</span><h1>Administração técnica</h1><p>Gerencie a estrutura e os acessos do sistema. Este perfil não recebe acesso automático aos dossiês.</p></div></header>
  <div class="notice privacy-admin"><strong>Separação de responsabilidades</strong><span>A administração configura contas e vínculos; os dados de acompanhamento permanecem protegidos pelas permissões do servidor.</span></div>
  <nav class="tabs admin-tabs" aria-label="Áreas da administração">@for(item of tabs;track item.id){<button type="button" [class.selected]="tab()===item.id" [attr.aria-current]="tab()===item.id?'page':null" (click)="tab.set(item.id)">{{item.label}}</button>}</nav>
  @if(tab()==='users'){
    <section class="card users-card"><div class="section-header"><div><h2>Contas cadastradas</h2><p>Perfis, campus e situação de acesso.</p></div><button (click)="showUserForm.set(true)">Nova conta</button></div>
      @if(loading()){<div class="loading-grid"><span class="skeleton skeleton-line"></span><span class="skeleton skeleton-card"></span></div>}@else if(users().length===0){<div class="empty-state"><span class="empty-state-mark">0</span><h3>Nenhuma conta cadastrada</h3><p>Crie a primeira conta institucional para começar.</p></div>}@else{<div class="table-wrap"><table class="mobile-cards"><thead><tr><th>Usuário</th><th>Campus</th><th>Perfis</th><th>Situação</th><th><span class="sr-only">Ações</span></th></tr></thead><tbody>@for(u of users();track u.id){<tr><td data-label="Usuário"><strong>{{u.name}}</strong><small>{{u.email}}</small></td><td data-label="Campus">{{campusLabel(u.campusId)}}</td><td data-label="Perfis"><div class="roles">@for(role of u.roles;track role){<span class="badge badge--info">{{label(role)}}</span>}</div></td><td data-label="Situação"><span [class]="u.active?'badge badge--success':'badge'">{{u.active?'Ativa':'Inativa'}}</span></td><td><div class="row"><button class="secondary compact" (click)="editAccess(u)">Acessos</button><button class="secondary compact" (click)="askToggle(u)">{{u.active?'Inativar':'Reativar'}}</button></div></td></tr>}</tbody></table></div>}
    </section>
  }
  @if(tab()==='campuses'){<section class="admin-grid"><form class="card stack" [formGroup]="campusForm" (ngSubmit)="createCampus()"><div class="section-header"><div><h2>Novo campus</h2><p>Cadastre uma unidade institucional.</p></div></div><label class="required">Nome<input formControlName="name"></label><label class="required">Código<input formControlName="code"></label><div><button [disabled]="campusForm.invalid||busy()">Criar campus</button></div></form><section class="card"><h2>Campi cadastrados</h2>@for(c of campuses();track c.id){<article class="campus-row"><div><strong>{{c.name}}</strong><small>{{c.code}}</small></div><span [class]="c.active?'badge badge--success':'badge'">{{c.active?'Ativo':'Inativo'}}</span></article>}</section></section>}
  @if(tab()==='academic'){<app-admin-academic />}
  @if(tab()==='references'){<app-admin-references />}
  @if(showUserForm()){<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="new-user-title"><div class="section-header"><div><span class="eyebrow">Conta institucional</span><h2 id="new-user-title">Criar nova conta</h2><p>A senha é temporária e deve ser comunicada por canal seguro.</p></div><button class="icon-button" (click)="showUserForm.set(false)" aria-label="Fechar">×</button></div><form class="stack" [formGroup]="userForm" (ngSubmit)="createUser()"><div class="grid two"><label class="required">Nome<input formControlName="name"></label><label class="required">E-mail<input type="email" formControlName="email"></label><label class="required">Senha temporária<input type="password" formControlName="password"><span class="field-hint">12 a 72 caracteres.</span></label><label>Campus<select formControlName="campusId"><option value="">Sem campus (admin técnico)</option>@for(c of campuses();track c.id){<option [value]="c.id">{{c.name}}</option>}</select></label><label class="required">Perfil inicial<select formControlName="role">@for(r of roles;track r.value){<option [value]="r.value">{{r.label}}</option>}</select></label></div><div class="dialog-actions"><button class="secondary" type="button" (click)="showUserForm.set(false)">Cancelar</button><button [disabled]="userForm.invalid||busy()">Criar conta</button></div></form></section></div>}
  @if(accessUser();as selected){<div class="modal-backdrop"><section class="modal access-modal" role="dialog" aria-modal="true" aria-labelledby="access-title"><div class="section-header"><div><span class="eyebrow">Perfis e segurança</span><h2 id="access-title">Acessos de {{selected.name}}</h2><p>{{selected.email}}</p></div><button class="icon-button" (click)="accessUser.set(null)" aria-label="Fechar">×</button></div><form class="stack" [formGroup]="permissionForm" (ngSubmit)="changeRoles()"><fieldset><legend>Perfis autorizados</legend><div class="role-checks">@for(r of roles;track r.value){<label><input type="checkbox" [checked]="permissionForm.controls.roles.value.includes(r.value)" (change)="toggleRole(r.value,$any($event.target).checked)"><span>{{r.label}}</span></label>}</div></fieldset><div><button [disabled]="permissionForm.controls.roles.value.length===0||busy()">Salvar perfis e revogar sessões</button></div></form><form class="security-box" (ngSubmit)="resetPassword()"><div><strong>Redefinir senha temporária</strong><p>A operação revoga as sessões atuais da conta.</p></div><label>Nova senha<input type="password" autocomplete="new-password" [formControl]="resetSecret"></label><button class="secondary" [disabled]="resetSecret.invalid||busy()">Redefinir senha</button></form></section></div>}
  <app-confirm-dialog [open]="toggleCandidate()!==null" [title]="toggleCandidate()?.active?'Inativar esta conta?':'Reativar esta conta?'" [description]="toggleDescription()" [confirmLabel]="toggleCandidate()?.active?'Inativar conta':'Reativar conta'" [danger]="toggleCandidate()?.active??false" (confirmed)="confirmToggle()" (cancelled)="toggleCandidate.set(null)" />
`,styles:[`.privacy-admin{display:grid;grid-template-columns:auto 1fr;gap:.8rem;margin-bottom:1rem}.privacy-admin span{color:var(--ink-600)}.admin-tabs{margin:0 0 1rem}.users-card{padding:0;overflow:hidden}.users-card .section-header{padding:1.25rem 1.5rem;margin:0}.users-card .table-wrap{border-radius:0;border-left:0;border-right:0;border-bottom:0}.users-card td strong,.users-card td small{display:block}.users-card td small{color:var(--ink-600)}.roles{display:flex;gap:.25rem;flex-wrap:wrap}.admin-grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem;align-items:start}.campus-row{display:flex;align-items:center;justify-content:space-between;padding:.85rem 0;border-top:1px solid var(--border)}.campus-row strong,.campus-row small{display:block}.campus-row small{color:var(--ink-600)}.role-checks{display:grid;grid-template-columns:1fr 1fr;gap:.5rem}.role-checks label{display:flex;align-items:center;border:1px solid var(--border);border-radius:.5rem;padding:.7rem}.role-checks input{width:auto}.security-box{display:grid;grid-template-columns:1fr 1fr auto;align-items:end;gap:1rem;background:var(--surface-soft);border:1px solid var(--border);border-radius:.75rem;padding:1rem}.security-box p{color:var(--ink-600);font-size:.82rem;margin:0}@media(max-width:800px){.admin-grid{grid-template-columns:1fr}.security-box{grid-template-columns:1fr}.role-checks{grid-template-columns:1fr}.privacy-admin{grid-template-columns:1fr}}` ]})
export class AdminComponent implements OnInit{
  private readonly api=inject(ApiService);private readonly fb=inject(FormBuilder);private readonly toast=inject(ToastService);readonly tabs=[{id:'users',label:'Usuários e acessos'},{id:'campuses',label:'Campi'},{id:'academic',label:'Cursos, componentes e vínculos'},{id:'references',label:'Cadastros de referência'}];readonly tab=signal('users');readonly roles=[{value:'ADMIN',label:'Administrador técnico'},{value:'NAPNE',label:'Equipe NAPNE'},{value:'COTEP',label:'COTEP'},{value:'COURSE_COORDINATOR',label:'Coordenação de curso'},{value:'TEACHER',label:'Professor'},{value:'TUTOR',label:'Monitor/Tutor'},{value:'MANAGEMENT',label:'Gestão'}];readonly users=signal<UserView[]>([]);readonly campuses=signal<Campus[]>([]);readonly loading=signal(true);readonly busy=signal(false);readonly showUserForm=signal(false);readonly accessUser=signal<UserView|null>(null);readonly toggleCandidate=signal<UserView|null>(null);readonly toggleDescription=computed(()=>{const u=this.toggleCandidate();return u?(u.active?`O acesso de ${u.name} será bloqueado e as sessões serão revogadas.`:`O acesso de ${u.name} será restaurado.`):''});readonly label=labelFor;readonly userForm=this.fb.nonNullable.group({name:['',Validators.required],email:['',[Validators.required,Validators.email]],password:['',[Validators.required,Validators.minLength(12),Validators.maxLength(72)]],campusId:[''],role:['NAPNE',Validators.required]});readonly permissionForm=this.fb.nonNullable.group({userId:['',Validators.required],roles:[[]as string[],Validators.required]});readonly resetSecret=this.fb.nonNullable.control('',[Validators.required,Validators.minLength(12),Validators.maxLength(72)]);readonly campusForm=this.fb.nonNullable.group({name:['',Validators.required],code:['',Validators.required]});
  ngOnInit(){this.load()}load(){this.loading.set(true);this.api.users().subscribe({next:v=>{this.users.set(v);this.loading.set(false)},error:e=>{this.loading.set(false);this.toast.show(errorMessage(e.status,'carregar as contas'),'error')}});this.api.campuses().subscribe({next:v=>this.campuses.set(v),error:e=>this.toast.show(errorMessage(e.status,'carregar os campi'),'error')})}campusLabel(id:number|null){return id===null?'Sem campus':this.campuses().find(c=>c.id===id)?.name??'Campus vinculado'}createUser(){if(this.userForm.invalid)return;const v=this.userForm.getRawValue();this.busy.set(true);this.api.createUser({name:v.name,email:v.email,password:v.password,campusId:v.campusId?Number(v.campusId):null,roles:[v.role]}).subscribe({next:()=>{this.userForm.reset({role:'NAPNE'});this.busy.set(false);this.showUserForm.set(false);this.toast.show('Conta criada com sucesso.','success');this.load()},error:e=>this.fail(e.status,'criar a conta')})}createCampus(){if(this.campusForm.invalid)return;this.busy.set(true);this.api.createCampus(this.campusForm.getRawValue()).subscribe({next:()=>{this.campusForm.reset();this.busy.set(false);this.toast.show('Campus criado com sucesso.','success');this.load()},error:e=>this.fail(e.status,'criar o campus')})}editAccess(u:UserView){this.accessUser.set(u);this.permissionForm.setValue({userId:String(u.id),roles:[...u.roles]});this.resetSecret.reset()}toggleRole(role:string,checked:boolean){const current=this.permissionForm.controls.roles.value;this.permissionForm.controls.roles.setValue(checked?[...current,role]:current.filter(v=>v!==role))}changeRoles(){const v=this.permissionForm.getRawValue();this.busy.set(true);this.api.setUserRoles(Number(v.userId),v.roles).subscribe({next:()=>{this.busy.set(false);this.accessUser.set(null);this.toast.show('Perfis atualizados e sessões revogadas.','success');this.load()},error:e=>this.fail(e.status,'salvar os perfis')})}resetPassword(){const user=this.accessUser();if(!user||this.resetSecret.invalid)return;this.busy.set(true);this.api.resetPassword(user.id,this.resetSecret.value).subscribe({next:()=>{this.busy.set(false);this.resetSecret.reset();this.toast.show('Senha temporária redefinida e sessões revogadas.','success')},error:e=>this.fail(e.status,'redefinir a senha')})}askToggle(u:UserView){this.toggleCandidate.set(u)}confirmToggle(){const u=this.toggleCandidate();if(!u)return;this.busy.set(true);this.toggleCandidate.set(null);this.api.setUserActive(u.id,!u.active).subscribe({next:()=>{this.busy.set(false);this.toast.show('Situação da conta atualizada.','success');this.load()},error:e=>this.fail(e.status,'alterar a situação da conta')})}private fail(status:number,action:string){this.busy.set(false);this.toast.show(errorMessage(status,action),'error')}
}
