import { Component, OnInit, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ApiService } from '../core/api.service';
import { Pei } from '../core/models';
import { errorMessage, labelFor, toneFor } from '../core/presentation';
import { ToastService } from '../core/toast.service';
import { ConfirmDialogComponent } from '../shared/confirm-dialog.component';

@Component({standalone:true,imports:[ReactiveFormsModule,RouterLink,ConfirmDialogComponent],template:`
  <a [routerLink]="['/estudantes',studentId]" class="back-link">← Voltar ao acompanhamento</a>
  @if(loading()){<div class="loading-grid"><span class="skeleton skeleton-card"></span><span class="skeleton skeleton-line"></span><span class="skeleton skeleton-card"></span></div>}
  @if(loadError()){<div class="error" role="alert"><strong>Não foi possível carregar o PEI.</strong><p>{{loadError()}}</p></div>}
  @if(pei();as value){
    <header class="pei-header"><div><span class="eyebrow">Plano de Ensino Individualizado</span><h1>Editor do PEI</h1><p>Período {{value.academicTerm}} · revisão {{value.revision}}</p></div><span [class]="'badge badge--'+tone(value.status)">{{label(value.status)}}</span></header>
    <div class="notice review-note" role="note"><span class="review-mark" aria-hidden="true">✓</span><div><strong>Revisão humana obrigatória</strong><p>Este rascunho apoia o planejamento pedagógico. Não representa diagnóstico e não substitui a análise do docente e da equipe responsável.</p></div></div>
    <form class="editor-layout" [formGroup]="form" (ngSubmit)="save()"><aside class="editor-nav card"><strong>Seções do documento</strong>@for(section of sections;track section.id){<a [href]="'#'+section.id">{{section.label}}</a>}<div class="document-state"><span>Estado atual</span><strong>{{label(value.status)}}</strong><small>Revisão {{value.revision}}</small></div></aside>
      <div class="editor-main stack">
        <section class="card form-section" id="overview"><div class="section-header"><div><span class="eyebrow">01 · Visão geral</span><h2>Direcionamento pedagógico</h2><p>Defina o objetivo central e as competências profissionais.</p></div></div><label class="required">Objetivo geral<textarea formControlName="generalObjectives"></textarea></label><label>Habilidades e competências profissionais<textarea formControlName="professionalSkills" placeholder="Uma habilidade por linha"></textarea></label></section>
        <section class="card form-section" id="objectives"><div class="section-header"><div><span class="eyebrow">02 · Objetivos</span><h2>Objetivos de aprendizagem</h2><p>Registre um objetivo por linha para facilitar a revisão.</p></div></div><div class="grid two"><label>Objetivos específicos<textarea formControlName="specificObjectives"></textarea></label><label>Objetivos não aplicáveis e justificativas<textarea formControlName="eliminatedObjectives"></textarea></label><label>Objetivos alternativos<textarea formControlName="alternativeObjectives"></textarea></label><label>Objetivos complementares<textarea formControlName="complementaryObjectives"></textarea></label></div></section>
        <section class="card form-section" id="content"><div class="section-header"><div><span class="eyebrow">03 · Conteúdo</span><h2>Organização curricular</h2></div></div><div class="grid two"><label>Ementa<textarea formControlName="syllabus"></textarea></label><label>Pré-requisitos<textarea formControlName="prerequisites"></textarea></label><label>Conteúdos prioritários<textarea formControlName="contents" placeholder="Um conteúdo por linha"></textarea></label></div></section>
        <section class="card form-section" id="strategies"><div class="section-header"><div><span class="eyebrow">04 · Estratégias</span><h2>Estratégias e recursos</h2></div></div><div class="grid two"><label>Estratégias facilitadoras<textarea formControlName="teachingStrategies" placeholder="Uma estratégia por linha"></textarea></label><label>Recursos metodológicos e assistivos<textarea formControlName="methodologicalResources" placeholder="Um recurso por linha"></textarea></label></div></section>
        <section class="card form-section" id="assessment"><div class="section-header"><div><span class="eyebrow">05 · Avaliação</span><h2>Avaliação e recuperação</h2></div></div><div class="grid two"><label>Critérios de avaliação<textarea formControlName="assessmentCriteria" placeholder="Um critério por linha"></textarea></label><label>Instrumentos de avaliação<textarea formControlName="assessmentInstruments" placeholder="Um instrumento por linha"></textarea></label><label>Recuperação diferenciada<textarea formControlName="recoveryProposal"></textarea></label></div></section>
        <section class="card form-section" id="bibliography"><div class="section-header"><div><span class="eyebrow">06 · Referências</span><h2>Bibliografia</h2></div></div><div class="grid two"><label>Bibliografia básica<textarea formControlName="basicBibliography" placeholder="Uma referência por linha"></textarea></label><label>Bibliografia complementar<textarea formControlName="complementaryBibliography" placeholder="Uma referência por linha"></textarea></label></div></section>
        <section class="card form-section" id="skills"><div class="section-header"><div><span class="eyebrow">07 · Inventário</span><h2>Habilidades e competências</h2><p>Registre a observação em cada dimensão. Todas as opções mantêm o significado institucional previsto.</p></div></div><div class="skills-grid">@for(dimension of dimensions;track dimension.key){<label>{{dimension.label}}<select [formControlName]="dimension.key"><option value="REALIZA_COM_AJUDA">Realiza com ajuda</option><option value="REALIZA_SEM_AJUDA">Realiza sem ajuda</option><option value="NAO_REALIZA">Não realiza</option><option value="NAO_OBSERVADO">Não foi observado</option></select></label>}</div></section>
        <div class="editor-actions"><div><strong>{{form.dirty?'Alterações ainda não salvas':'Revisão atual salva'}}</strong><small>{{form.dirty?'Salve uma nova revisão antes de aprovar.':'A aprovação pode ser registrada após a conferência.'}}</small></div><button type="submit" [disabled]="saving()||isLocked()">@if(saving()){<span class="spinner"></span>}Salvar como nova revisão</button><button type="button" class="approve" (click)="requestApproval()" [disabled]="saving()||isLocked()||value.status==='APPROVED'">Aprovar após revisão</button></div>
      </div>
    </form>
  }
  <app-confirm-dialog [open]="approvalPending()" title="Aprovar esta revisão do PEI?" description="A aprovação registra sua identidade e a data da revisão humana. Confirme somente após conferir todo o documento." confirmLabel="Aprovar PEI" (confirmed)="approve()" (cancelled)="approvalPending.set(false)" />
`,styles:[`.back-link{display:inline-flex;margin-bottom:1rem;font-weight:700;text-decoration:none}.pei-header{display:flex;align-items:flex-end;justify-content:space-between;gap:1rem;margin-bottom:1rem}.pei-header p{color:var(--ink-600);margin:0}.review-note{display:flex;gap:1rem;margin-bottom:1rem}.review-note p{margin:.2rem 0 0}.review-mark{width:2.4rem;height:2.4rem;display:grid;place-items:center;border-radius:50%;background:#fff;color:var(--info);font-weight:900;flex:none}.editor-layout{display:grid;grid-template-columns:14.5rem minmax(0,1fr);gap:1rem;align-items:start}.editor-nav{position:sticky;top:5.75rem;display:grid;gap:.2rem;padding:1rem}.editor-nav>a{padding:.45rem .55rem;border-radius:.4rem;text-decoration:none;font-size:.86rem}.editor-nav>a:hover{background:var(--primary-50)}.document-state{border-top:1px solid var(--border);margin-top:.75rem;padding:.8rem .55rem 0}.document-state span,.document-state strong,.document-state small{display:block}.document-state span,.document-state small{color:var(--ink-600);font-size:.75rem}.form-section{scroll-margin-top:6rem}.skills-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.75rem}.editor-actions{position:sticky;bottom:1rem;z-index:10;display:grid;grid-template-columns:1fr auto auto;align-items:center;gap:.75rem;background:var(--primary-950);color:#fff;border-radius:var(--radius-lg);padding:1rem;box-shadow:var(--shadow-md)}.editor-actions strong,.editor-actions small{display:block}.editor-actions small{color:#c7ddd6}.editor-actions .approve{background:#fff;color:var(--primary-900)}@media(max-width:950px){.editor-layout{grid-template-columns:1fr}.editor-nav{position:static;display:flex;overflow:auto}.editor-nav>strong,.document-state{display:none}.editor-actions{grid-template-columns:1fr 1fr}.editor-actions>div{grid-column:1/-1}}@media(max-width:700px){.pei-header{align-items:flex-start;flex-direction:column}.skills-grid{grid-template-columns:1fr}.editor-actions{position:static;grid-template-columns:1fr}.editor-actions>div{grid-column:auto}.editor-actions button{width:100%}}` ]})
export class PeiEditorComponent implements OnInit{
  private readonly route=inject(ActivatedRoute);private readonly api=inject(ApiService);private readonly fb=inject(FormBuilder);private readonly router=inject(Router);private readonly toast=inject(ToastService);readonly sections=[{id:'overview',label:'Visão geral'},{id:'objectives',label:'Objetivos'},{id:'content',label:'Conteúdo'},{id:'strategies',label:'Estratégias e recursos'},{id:'assessment',label:'Avaliação'},{id:'bibliography',label:'Bibliografia'},{id:'skills',label:'Inventário de habilidades'}];readonly dimensions=[{key:'oralCommunication',label:'Comunicação oral'},{key:'readingAndWriting',label:'Leitura e produção textual'},{key:'logicalMathematicalReasoning',label:'Raciocínio lógico-matemático'},{key:'socioemotionalSkills',label:'Habilidades socioemocionais'},{key:'functionalAutonomy',label:'Autonomia funcional'},{key:'digitalTechnologies',label:'Tecnologias digitais'}];readonly studentId=Number(this.route.snapshot.paramMap.get('studentId'));peiId=String(this.route.snapshot.paramMap.get('peiId'));readonly pei=signal<Pei|null>(null);readonly loading=signal(true);readonly loadError=signal('');readonly saving=signal(false);readonly approvalPending=signal(false);readonly label=labelFor;readonly tone=toneFor;readonly isLocked=computed(()=>['ARCHIVED','SUPERSEDED'].includes(this.pei()?.status??''));private rawContent:Record<string,unknown>={};
  readonly form=this.fb.nonNullable.group({generalObjectives:['',Validators.required],specificObjectives:[''],eliminatedObjectives:[''],alternativeObjectives:[''],complementaryObjectives:[''],professionalSkills:[''],syllabus:[''],prerequisites:[''],contents:[''],teachingStrategies:[''],methodologicalResources:[''],assessmentCriteria:[''],assessmentInstruments:[''],recoveryProposal:[''],basicBibliography:[''],complementaryBibliography:[''],oralCommunication:[''],readingAndWriting:[''],logicalMathematicalReasoning:[''],socioemotionalSkills:[''],functionalAutonomy:[''],digitalTechnologies:['']});
  ngOnInit(){this.route.paramMap.subscribe(params=>{this.peiId=String(params.get('peiId'));this.loading.set(true);this.loadError.set('');this.api.pei(this.studentId,this.peiId).subscribe({next:p=>{this.pei.set(p);this.rawContent=p.content;this.fill(p.content);this.form.markAsPristine();this.loading.set(false)},error:e=>{this.loading.set(false);this.loadError.set(errorMessage(e.status,'carregar o PEI'))}})})}save(){this.form.markAllAsTouched();this.saving.set(true);this.api.revisePei(this.studentId,this.peiId,{status:this.form.valid?'IN_REVIEW':'DRAFT',content:this.content()}).subscribe({next:p=>{this.saving.set(false);this.pei.set(p);this.rawContent=p.content;this.form.markAsPristine();void this.router.navigate(['/estudantes',this.studentId,'pei',p.id]);this.toast.show('Nova revisão do PEI salva com sucesso.','success')},error:e=>{this.saving.set(false);this.toast.show(errorMessage(e.status,'salvar a revisão'),'error')}})}requestApproval(){if(this.form.dirty){this.toast.show('Salve as alterações como uma nova revisão antes de aprovar.','error');return}this.approvalPending.set(true)}approve(){this.approvalPending.set(false);this.saving.set(true);this.api.approvePei(this.studentId,this.peiId).subscribe({next:p=>{this.pei.set(p);this.saving.set(false);this.toast.show('PEI aprovado. A revisão humana foi registrada.','success')},error:e=>{this.saving.set(false);this.toast.show(errorMessage(e.status,'aprovar o PEI'),'error')}})}
  private content(){const v=this.form.getRawValue(),lines=(s:string)=>s.split('\n').map(x=>x.trim()).filter(Boolean);return{...this.rawContent,generalObjectives:v.generalObjectives,specificObjectives:lines(v.specificObjectives),eliminatedObjectives:lines(v.eliminatedObjectives),alternativeObjectives:lines(v.alternativeObjectives),complementaryObjectives:lines(v.complementaryObjectives),professionalSkills:lines(v.professionalSkills),syllabus:v.syllabus,prerequisites:v.prerequisites,contents:lines(v.contents),teachingStrategies:lines(v.teachingStrategies),methodologicalResources:lines(v.methodologicalResources),assessmentCriteria:lines(v.assessmentCriteria),assessmentInstruments:lines(v.assessmentInstruments),recoveryProposal:v.recoveryProposal,basicBibliography:lines(v.basicBibliography),complementaryBibliography:lines(v.complementaryBibliography),skillsInventory:{oralCommunication:v.oralCommunication,readingAndWriting:v.readingAndWriting,logicalMathematicalReasoning:v.logicalMathematicalReasoning,socioemotionalSkills:v.socioemotionalSkills,functionalAutonomy:v.functionalAutonomy,digitalTechnologies:v.digitalTechnologies}}}private fill(c:Record<string,unknown>){const text=(key:string)=>Array.isArray(c[key])?(c[key]as unknown[]).join('\n'):typeof c[key]==='object'?JSON.stringify(c[key],null,2):String(c[key]??''),inventory=(c['skillsInventory']??{})as Record<string,unknown>;this.form.patchValue({generalObjectives:text('generalObjectives'),specificObjectives:text('specificObjectives'),eliminatedObjectives:text('eliminatedObjectives'),alternativeObjectives:text('alternativeObjectives'),complementaryObjectives:text('complementaryObjectives'),professionalSkills:text('professionalSkills'),syllabus:text('syllabus'),prerequisites:text('prerequisites'),contents:text('contents'),teachingStrategies:text('teachingStrategies'),methodologicalResources:text('methodologicalResources'),assessmentCriteria:text('assessmentCriteria'),assessmentInstruments:text('assessmentInstruments'),recoveryProposal:text('recoveryProposal'),basicBibliography:text('basicBibliography'),complementaryBibliography:text('complementaryBibliography'),oralCommunication:this.join(inventory['oralCommunication']),readingAndWriting:this.join(inventory['readingAndWriting']),logicalMathematicalReasoning:this.join(inventory['logicalMathematicalReasoning']),socioemotionalSkills:this.join(inventory['socioemotionalSkills']),functionalAutonomy:this.join(inventory['functionalAutonomy']),digitalTechnologies:this.join(inventory['digitalTechnologies'])})}private join(v:unknown){return typeof v==='string'?v:'NAO_OBSERVADO'}
}
