services:
  app:
    image: mcr.microsoft.com/devcontainers/java:21
    command: sleep infinity
    depends_on:
      - mysql
    ports:
      - "9000:9000"
      - "4200:4200"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: napne360
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    ports:
      - "8080:80"

volumes:
  mysql-data: